### ISSUE TITLE
Restore master to PostScript curves

### ISSUE THREAD

**Issue by kateliev** [googlefonts/science-gothic#279]
I do not know how, when and why this happened, but the current source is in TrueType (TT) curve format. I have a hunch that it is a purposely made decision, but cannot seem to find any written record of it? 

Nevertheless i strongly believe that we should keep the source in PostScript (PS). Otherwise it will be hard for us and those after us to maintain the project. 

_Working in PS would be far more easier for us the designers to do our job, also the tools that we are using are fine tuned to work with PS curves - for example we cannot use a third of the tools provided by TypeRig (TR) and our TR based tools. Also i believe we have drawing guidelines and tool presets based on PS design like handle length on rounded corners and etc.. that are now inapplicable to the current TT curves..._

@tphinney i have already forked the current repository and took the appropriate actions to build us a PS based master file. _Unless we find a source file with PS laying around somewhere - i surely do not have one..._ This will require the following steps:

- [x] Find a desirable PS flavored source in the repo: Already did this using df32f66df5df9fd04574e89528640da7290b2f08
- [x] Copy all features data;
- [x] Copy all classes data;
- [x] Copy all current kerning data  #222 using 605089ebfd75245814b55b522e4457f2cd4dc325;
- [x] Propagate changes made by @tphinney for the following issues:  
- [x] Commit 462267232e5ad5a7a78551c8f9edc2a3639aaf71 fixing #235, #233, #253;
- [x] Commit df32f66df5df9fd04574e89528640da7290b2f08 fixing #252, #255, #251, #254, #233;

_As most of these were a font metadata fixes, i have transferred all current metadata to the font i am using, but am leaving it to @tphinney to verify that (and checkboxes to check)_

**Comment by tphinney** [comment]
Some of the font metadata still needed fixing. All done now, will check in VFC source v1.003
